"use server"

import { revalidatePath } from "next/cache"
import { createClient } from "@/lib/supabase/server"
import { ActionResult } from "@/lib/types"
import { redirect } from "next/navigation"

export async function createGroup(prevState: ActionResult<{ id: string }>, formData: FormData): Promise<ActionResult<{ id: string }>> {
  const name = formData.get("name") as string
  const description = formData.get("description") as string
  const privacy = formData.get("privacy") as 'public' | 'private'

  if (!name || name.trim().length === 0) {
    return { error: "Group name is required" }
  }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Unauthorized" }

  // Create group
  const { data: newGroup, error: groupError } = await supabase
    .from("groups")
    .insert({
      name: name.trim(),
      description: description.trim(),
      privacy: privacy || 'public',
      created_by: user.id
    })
    .select('id')
    .single()

  if (groupError || !newGroup) return { error: groupError?.message || "Failed to create group" }

  // Add creator as admin
  await supabase
    .from("group_members")
    .insert({
      group_id: newGroup.id,
      user_id: user.id,
      role: 'admin'
    })

  revalidatePath("/groups")
  redirect(`/groups/${newGroup.id}`)
}

export async function joinGroup(groupId: string): Promise<ActionResult> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Unauthorized" }

  const { error } = await supabase
    .from("group_members")
    .insert({
      group_id: groupId,
      user_id: user.id,
      role: 'member'
    })

  if (error) {
    if (error.code === '23505') return { error: "Already a member" }
    return { error: error.message }
  }

  revalidatePath(`/groups/${groupId}`)
  revalidatePath("/groups")
  return {}
}

export async function leaveGroup(groupId: string): Promise<ActionResult> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Unauthorized" }

  const { error } = await supabase
    .from("group_members")
    .delete()
    .eq("group_id", groupId)
    .eq("user_id", user.id)

  if (error) return { error: error.message }

  revalidatePath(`/groups/${groupId}`)
  revalidatePath("/groups")
  return {}
}

export async function createInviteLink(groupId: string): Promise<ActionResult<{ code: string }>> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: "Unauthorized" }

  // Verify user is admin
  const { data: membership } = await supabase
    .from("group_members")
    .select("role")
    .eq("group_id", groupId)
    .eq("user_id", user.id)
    .single()

  if (!membership || membership.role !== 'admin') {
    return { error: "Only admins can create invite links" }
  }

  // Create invite (code is auto-generated by default in DB)
  const { data: invite, error } = await supabase
    .from("group_invites")
    .insert({
      group_id: groupId,
      created_by: user.id
    })
    .select('invite_code')
    .single()

  if (error || !invite) return { error: error?.message || "Failed to create invite" }

  return { data: { code: invite.invite_code } }
}
